(deftheme deeper-blue
  "Created 2020-03-12.")

(custom-theme-set-faces
 'deeper-blue
 '(cursor ((t (:background "dark gray"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "seashell4"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "grey60"))))
 '(diff-function ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-header ((((class color) (min-colors 89)) (:background "grey45"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:inherit diff-header))))
 '(diff-index ((((class color) (min-colors 89)) (:inherit diff-file-header))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "white" :background "darkolivegreen"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:foreground "white" :background "dodgerblue4"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "white" :background "indianred4"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((t (:foreground "dark violet"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(fringe ((((class color) (min-colors 89)) (:background "black"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(default ((((class color) (min-colors 89)) (:background "#181a26" :foreground "gray80")))))

(provide-theme 'deeper-blue)
