#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Kill picom
# pkill picom 
# picom -b

# No gap
bspc config window_gap 2
bspc config border_width 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Orange-ish highlight
bspc config focused_border_color "#eeaa44"

# Dual monitor setup

external_monitor=$(xrandr --query | grep 'HDMI-1' | grep -e "\bconnected")
if [[ $external_monitor ]]; then
	bspc monitor HDMI-1 -d 1 2 3 4 5
	bspc monitor eDP-1 -d 6 7 8 9 0
	xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
	xrandr --output eDP-1 --mode 1920x1080 --rotate normal
fi

# Polybar
if [ -x /usr/bin/polybar ]; then
	bash $HOME/.config/polybar/launch.sh
fi

~/utils/wallpaper.sh

# Other stuff
numlockx on

# xsetroot -cursor_name left_ptr &
light-locker --lock-on-suspend &
